### ISSUE TITLE
doesn't work with artifact registry

### ISSUE THREAD

**Issue by sean-dbk** [tammert/replicant#3]
```yaml
config:
  images:
    influxdb:
      source: docker.io/influxdb
      destination: europe-west4-docker.pkg.dev/$project/replicant/influxdb
      allow-prerelease: true
```

I was expecting at least a proper failure

```
master » k logs -f e-x9zcc
...
time="2021-05-12T12:29:27Z" level=debug msg="image europe-west4-docker.pkg.dev/debijenkorf-io/replicant/influxdb:2.0.6 already present in destination repository"

master » gcrane ls europe-west4-docker.pkg.dev/debijenkorf-io/replicant                

master » gcloud artifacts packages list --repository replicant --location europe-west4
Listing items under project $project, location europe-west4, repository replicant.

Listed 0 items.
```
